import { MoodThemeId, ThemeConfig } from '@sur-o-jhankaar/shared-types';

export const THEME_REGISTRY: Record<MoodThemeId, ThemeConfig> = {
  cinematic_gold_maroon: {
    id: 'cinematic_gold_maroon',
    name: 'Cinematic Gold & Maroon',
    description: 'Soft spotlight glow, film-era atmosphere, floating golden particles, subtle lens flare.',
    backgroundType: 'cinematic',
    palette: ['#2A0810', '#54151C', '#9E2A2B', '#D39B3D', '#F4D06F'],
    accentColor: '#D39B3D',
    glowColor: 'rgba(211, 155, 61, 0.45)',
    textColor: '#FFF8EB',
    animation: 'spotlight',
    particleEffect: 'dust',
    grain: true,
    motionIntensity: 'low',
    cssVariables: {
      '--bg-primary': '#1A0409',
      '--bg-surface': '#2D0A13',
      '--bg-card': '#3D101C',
      '--text-primary': '#FFF8EB',
      '--text-secondary': '#D4AF87',
      '--accent': '#D39B3D',
      '--accent-hover': '#F4D06F',
      '--glow-color': 'rgba(211, 155, 61, 0.35)',
      '--border-color': 'rgba(211, 155, 61, 0.2)'
    }
  },
  dusty_sepia_vhs: {
    id: 'dusty_sepia_vhs',
    name: 'Dusty Sepia VHS',
    description: 'Dusty sepia, VHS scanlines, old-film texture, slow horizontal drift, warm faded highlights.',
    backgroundType: 'vhs',
    palette: ['#241A13', '#4A3525', '#7A5B3E', '#BA9B77', '#E8D8C8'],
    accentColor: '#BA9B77',
    glowColor: 'rgba(186, 155, 119, 0.35)',
    textColor: '#FAF4EC',
    animation: 'drift',
    particleEffect: 'dust',
    grain: true,
    motionIntensity: 'low',
    cssVariables: {
      '--bg-primary': '#16100B',
      '--bg-surface': '#261B12',
      '--bg-card': '#38281B',
      '--text-primary': '#FAF4EC',
      '--text-secondary': '#C4B29E',
      '--accent': '#BA9B77',
      '--accent-hover': '#E2CEB5',
      '--glow-color': 'rgba(186, 155, 119, 0.3)',
      '--border-color': 'rgba(186, 155, 119, 0.2)'
    }
  },
  vibrant_folk_festival: {
    id: 'vibrant_folk_festival',
    name: 'Vibrant Folk Festival',
    description: 'Vibrant folk color-blocks, energetic particles, traditional shapes, festive lively motion.',
    backgroundType: 'folk',
    palette: ['#2B0C03', '#8A1C05', '#D84315', '#FF8F00', '#FFD54F'],
    accentColor: '#FF8F00',
    glowColor: 'rgba(255, 143, 0, 0.5)',
    textColor: '#FFFFFF',
    animation: 'festival',
    particleEffect: 'spark',
    grain: false,
    motionIntensity: 'high',
    cssVariables: {
      '--bg-primary': '#1F0802',
      '--bg-surface': '#3A1005',
      '--bg-card': '#541707',
      '--text-primary': '#FFFFFF',
      '--text-secondary': '#FFC48C',
      '--accent': '#FF8F00',
      '--accent-hover': '#FFB300',
      '--glow-color': 'rgba(255, 143, 0, 0.45)',
      '--border-color': 'rgba(255, 143, 0, 0.25)'
    }
  },
  earthy_terracotta_river: {
    id: 'earthy_terracotta_river',
    name: 'Earthy Terracotta River',
    description: 'Earthy terracotta, muted natural river teal, folk-art motifs, slow organic movement.',
    backgroundType: 'terracotta',
    palette: ['#1C100C', '#4E2415', '#8D4024', '#2E6F68', '#A2B9B4'],
    accentColor: '#2E6F68',
    glowColor: 'rgba(46, 111, 104, 0.4)',
    textColor: '#F5ECE7',
    animation: 'organic_drift',
    particleEffect: 'none',
    grain: true,
    motionIntensity: 'low',
    cssVariables: {
      '--bg-primary': '#140C09',
      '--bg-surface': '#251610',
      '--bg-card': '#3B2117',
      '--text-primary': '#F5ECE7',
      '--text-secondary': '#C2A79B',
      '--accent': '#3D8C83',
      '--accent-hover': '#5DB3A9',
      '--glow-color': 'rgba(61, 140, 131, 0.35)',
      '--border-color': 'rgba(61, 140, 131, 0.2)'
    }
  },
  neon_teal_purple_city: {
    id: 'neon_teal_purple_city',
    name: 'Neon Teal Purple City',
    description: 'Neon teal/purple, city-night glow, light trails, modern urban subtle geometric motion.',
    backgroundType: 'neon',
    palette: ['#0A091A', '#1E123D', '#4A148C', '#00E5FF', '#D500F9'],
    accentColor: '#00E5FF',
    glowColor: 'rgba(0, 229, 255, 0.5)',
    textColor: '#F3F4F6',
    animation: 'light_trails',
    particleEffect: 'light',
    grain: false,
    motionIntensity: 'medium',
    cssVariables: {
      '--bg-primary': '#070614',
      '--bg-surface': '#120E2E',
      '--bg-card': '#1E174B',
      '--text-primary': '#F3F4F6',
      '--text-secondary': '#B3A6DC',
      '--accent': '#00E5FF',
      '--accent-hover': '#80F0FF',
      '--glow-color': 'rgba(0, 229, 255, 0.4)',
      '--border-color': 'rgba(0, 229, 255, 0.25)'
    }
  },
  sepia_ivory_gramophone: {
    id: 'sepia_ivory_gramophone',
    name: 'Sepia Ivory Gramophone',
    description: 'Sepia/ivory, gramophone-era paper texture, vinyl rotation vibes, slow elegant movement.',
    backgroundType: 'sepia',
    palette: ['#1E1610', '#3E2E20', '#74563C', '#B59470', '#F4EBD9'],
    accentColor: '#B59470',
    glowColor: 'rgba(181, 148, 112, 0.4)',
    textColor: '#FDFBF7',
    animation: 'vinyl_rotate',
    particleEffect: 'dust',
    grain: true,
    motionIntensity: 'low',
    cssVariables: {
      '--bg-primary': '#140E0A',
      '--bg-surface': '#241B13',
      '--bg-card': '#36281C',
      '--text-primary': '#FDFBF7',
      '--text-secondary': '#CFBEAC',
      '--accent': '#B59470',
      '--accent-hover': '#D8BDA0',
      '--glow-color': 'rgba(181, 148, 112, 0.3)',
      '--border-color': 'rgba(181, 148, 112, 0.2)'
    }
  },
  deep_indigo_radio: {
    id: 'deep_indigo_radio',
    name: 'Deep Indigo Radio',
    description: 'Deep indigo, vintage radio-dial glow, analog frequency markings, soft waveform pulses.',
    backgroundType: 'indigo',
    palette: ['#0A0F1D', '#121D38', '#1E325C', '#38EF7D', '#11998E'],
    accentColor: '#38EF7D',
    glowColor: 'rgba(56, 239, 125, 0.45)',
    textColor: '#E8F5E9',
    animation: 'dial_pulse',
    particleEffect: 'light',
    grain: true,
    motionIntensity: 'low',
    cssVariables: {
      '--bg-primary': '#060A14',
      '--bg-surface': '#0E172C',
      '--bg-card': '#162343',
      '--text-primary': '#E8F5E9',
      '--text-secondary': '#9EC1A3',
      '--accent': '#38EF7D',
      '--accent-hover': '#69F0AE',
      '--glow-color': 'rgba(56, 239, 125, 0.35)',
      '--border-color': 'rgba(56, 239, 125, 0.25)'
    }
  },
  cream_green_tagore: {
    id: 'cream_green_tagore',
    name: 'Cream Green Tagore',
    description: 'Soft cream/muted green, floating leaf motifs, Tagore-era literary typography, peaceful motion.',
    backgroundType: 'cream',
    palette: ['#131B17', '#25352E', '#3B5249', '#8CA394', '#E8E5DA'],
    accentColor: '#8CA394',
    glowColor: 'rgba(140, 163, 148, 0.35)',
    textColor: '#F7F6F2',
    animation: 'leaf_float',
    particleEffect: 'leaf',
    grain: true,
    motionIntensity: 'low',
    cssVariables: {
      '--bg-primary': '#0D1310',
      '--bg-surface': '#1A2520',
      '--bg-card': '#273831',
      '--text-primary': '#F7F6F2',
      '--text-secondary': '#BFCAC2',
      '--accent': '#8CA394',
      '--accent-hover': '#B0C4B7',
      '--glow-color': 'rgba(140, 163, 148, 0.25)',
      '--border-color': 'rgba(140, 163, 148, 0.2)'
    }
  },
  deep_red_gold_temple: {
    id: 'deep_red_gold_temple',
    name: 'Deep Red & Gold Temple',
    description: 'Deep red/gold, temple lamp flicker, incense-smoke particles, soft divine glow, ceremonial motion.',
    backgroundType: 'temple',
    palette: ['#200407', '#500B11', '#85131C', '#E5A93C', '#FCD34D'],
    accentColor: '#E5A93C',
    glowColor: 'rgba(229, 169, 60, 0.5)',
    textColor: '#FFFBF0',
    animation: 'lamp_flicker',
    particleEffect: 'smoke',
    grain: true,
    motionIntensity: 'medium',
    cssVariables: {
      '--bg-primary': '#140204',
      '--bg-surface': '#2A060A',
      '--bg-card': '#40090F',
      '--text-primary': '#FFFBF0',
      '--text-secondary': '#E3B87D',
      '--accent': '#E5A93C',
      '--accent-hover': '#FCD34D',
      '--glow-color': 'rgba(229, 169, 60, 0.4)',
      '--border-color': 'rgba(229, 169, 60, 0.25)'
    }
  },
  near_black_story_spotlight: {
    id: 'near_black_story_spotlight',
    name: 'Near-Black Story Spotlight (Sunday Suspense)',
    description: 'Near-black storytelling room, single warm spotlight, minimal movement, waveform pulse.',
    backgroundType: 'spotlight',
    palette: ['#070709', '#121216', '#22222B', '#E09F3E', '#F4F1DE'],
    accentColor: '#E09F3E',
    glowColor: 'rgba(224, 159, 62, 0.4)',
    textColor: '#F4F1DE',
    animation: 'story_spotlight',
    particleEffect: 'none',
    grain: true,
    motionIntensity: 'low',
    cssVariables: {
      '--bg-primary': '#050507',
      '--bg-surface': '#0E0E12',
      '--bg-card': '#181820',
      '--text-primary': '#F4F1DE',
      '--text-secondary': '#A5A299',
      '--accent': '#E09F3E',
      '--accent-hover': '#F3C96B',
      '--glow-color': 'rgba(224, 159, 62, 0.35)',
      '--border-color': 'rgba(224, 159, 62, 0.15)'
    }
  }
};

export const DEFAULT_THEME_ID: MoodThemeId = 'cinematic_gold_maroon';
export const DEFAULT_THEME = THEME_REGISTRY[DEFAULT_THEME_ID];
